### ISSUE TITLE
Errata Programación modular (I)

### ISSUE THREAD

**Issue by edumarrom** [ricpelo/pro#4]
Buenas tardes. Estoy estudiando la nueva unidad. Me encuentro en el punto 4.5.2. Acoplamiento. Tras enunciar la escala de acoplamiento, el siguiente parrafo es el mismo que el que precede a la escala de cohesión.
Dejo aquí enlace directo a la página que menciono:
[https://pro.iesdonana.org/slides/programacion-modular-i.html#/5/22](https://pro.iesdonana.org/slides/programacion-modular-i.html#/5/22)

**Comment by ricpelo** [comment]
Tienes toda la razón. Se hizo un «copia y pega» y no se arregló después. Ya está corregido. ¡Muchas gracias!
